#!/bin/sh

if [ ! -x ./acl ]
then
	echo Compile ./acl first
	exit 1
fi

if [ ! -d ./tests.output ]
then
	mkdir ./tests.output
fi

for TNAME in tests.in/[0-9][0-9][0-9]
do
	OUTPUT=`basename $TNAME`
	echo "Running test $OUTPUT"
	./acl -p < $TNAME > tests.output/$OUTPUT 
	if [ "$?" != "0" ]
	then
		XSTATUS=$?
		echo Test $OUTPUT exited with non-zero status $XSTATUS
	fi
	DESIRED=tests.out/$OUTPUT
	if [ -r $DESIRED ]
	then
		if diff $DESIRED tests.output/$OUTPUT > /dev/null
		then
			:
		else
			echo "Test $OUTPUT failed"
		fi
	else
		echo "No desired output specified for $OUTPUT"
	fi
done

# Put some coverage tests here that exercize setting command line flags
./acl -p -x > /dev/null 2>&1
./acl -p -c -d -e -N 10 -s -T 150 -t < /dev/null 2>&1
